### ISSUE TITLE
I get EOFError when I read logs

### ISSUE THREAD

**Issue by moimran** [jasonish/py-idstools#21]
root@snort1:/etc/snort# idstools-u2json -C /etc/snort/classification.config -S /etc/snort/sid-msg.map -G /etc/snort/gen-msg.map /var/log/snort/snort.log.1454584880
INFO: Loaded 514 rule message map entries.
INFO: Loaded 38 classifications.
Traceback (most recent call last):
  File "/usr/local/bin/idstools-u2json", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/idstools/scripts/u2json.py", line 308, in main
    for record in reader:
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 586, in next
    record = self.reader.next()
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 549, in next
    return read_record(self.fileobj)
  File "/usr/local/lib/python2.7/dist-packages/idstools/unified2.py", line 522, in read_record
    raise err
EOFError

**Comment by jasonish** [comment]
I doubt this is an issue. It looks as though the last record in the file isn't complete, so an EOFError is thrown.  I could make the error message a little more meaningful in idstools-u2json though.

If you believe the last record is complete, and u2json is erroring when it shouldn't, I'll need a sample log file.

Other reasons for this error could be that the file is growing while its being read, or the file is not a unified2 file.

**Comment by jasonish** [comment]
My guess is that /var/log/snort/snort.log.1454584880 is a tcpdump file, and not a unified2 file.

**Comment by moimran** [comment]
Thanks for replying jsonish, Yes may be you are right , I have attached a ZIP file (Actually a winrar file as rar is not supported by github I had to change extension to zip) it has the snort.log file and also I have attached my snort.conf file for reference.

Please suggest me what would be the config for unified2 in snort.conf in case it is wrong.

Appreciate your help, if this works we are going to use your module heavily.
[snort.log.zip](https://github.com/jasonish/py-idstools/files/118549/snort.log.zip)

**Comment by moimran** [comment]
You are right that file is a capture, I was able to open it with wireshark file.But I was trying to generate 
alert_unified2 , for some reason I dont see that file being created.

 output alert_unified2: filename snort.u2, limit 128, nostamp
 output log_unified2: filename snort.log, limit 128, nostamp

In the local.rules I created this entry to logs all the alerts.
alert tcp any any -> any 80 (msg:"TCP test detected"; GID:2; sid:10000002; rev:001; classtype:tcp-connection;)
I see this slert being generated
02/05-07:32:38.000000  [**] [2:10000002:1] TCP test detected [**] [Classification: A TCP connection was detected] [Priority: 4] {TCP} 30.1.1.2:14087 -> 20.1.1.3:80
But I dont see alert.u2 created, am I missing something.
The Aim is to generate continuous JSON format alerts.

**Comment by jasonish** [comment]
I'd use the default line:

output unified2: filename merged.log, limit 128, nostamp, mpls_event_types, vlan_event_types

but remove the nostamp option so you get timestamped files, so:

output unified2: filename merged.log, limit 128, mpls_event_types, vlan_event_types

Then you should be able to run idstools-u2json on the merged.log.

**Comment by moimran** [comment]
got it my bad I was using _A console.. i the snort command.. so all output was going to console.. but I was expecting it would also send to unified2.

Sorry to bother you.. thanks for your time..

**Comment by jasonish** [comment]
No problem.
