### ISSUE TITLE
unified2 extra data invalid field amount

### ISSUE THREAD

**Issue by TheShankapotomus** [jasonish/py-idstools#25]
According to the docs https://www.snort.org/faq/readme-unified2/ and http://manual-snort-org.s3-website-us-east-1.amazonaws.com/node44.html the Extra Data record only supports 24 bytes where your EXTRA_DATA_FIELDS enum contains 32, the first two fields (event-type, event-length) do not appear to be documented. As these two sites differ in portions referencing the same events it could be a documentation issue and not your code.

**Comment by jasonish** [comment]
I'm not sure why its documented that way. Each extra data record (as documented) is preceded by an extra data header that contains the event-type and event-length. I just consolidated them into the extra data record.

See:
https://github.com/jasonish/snort/blob/master/src/sfutil/Unified2_common.h#L149

**Comment by TheShankapotomus** [comment]
Thank for looking into that!
