### ISSUE TITLE
[Feature Request] Request for DROP handling

### ISSUE THREAD

**Issue by samiux** [jasonish/py-idstools#26]
I would like to request a drop.conf for changing all/some/specified "alert" rules to "drop" rules.

**Comment by jasonish** [comment]
I've committed support for this to master, you can update like 

pip install --upgrade https://github.com/jasonish/py-idstools/archive/master.zip

Create a file "drop.conf", the format is the same as enable.conf or disable.conf, then provide it on the command with --drop=drop.conf.

Only lightly tested.
