### ISSUE TITLE
IPV6 error

### ISSUE THREAD

**Issue by ddehban** [jasonish/py-idstools#29]
based on my checking on unified2.py the EVENT_IP6_FIELDS should be fixed:

```
Field("source-ip.raw", 4, "16s"),   --->    Field("source-ip.raw", 16, "16s"),
Field("destination-ip.raw", 4, "16s"),    --->    Field("destination-ip.raw", 16, "16s"), 
```

otherwise these errors will be return:
`"struct.error: unpack requires a bytes object of length 76" on line 343`

format is '>LLLLLLLLL16s16sHHBBBB' and len(buf) should be 76 but self.fixed_len is 52 now

**Comment by jasonish** [comment]
Thanks, this is now fixed in master.  I'll probably tag a release for it soon.
