### ISSUE TITLE
IP6 V2 Event does not unpack properly

### ISSUE THREAD

**Issue by aaron-kahn** [jasonish/py-idstools#30]
When reading a unified2 log from Snort, the `decode_record` function fails with the following error:

`struct.error: unpack requires a bytes object of length 84`

The `EVENT_IP6_FIELDS` tuple tells the decoder to look for only 64 bytes. I am not sure if this is because of the sensor I used or because Snort has changed the signature. I fixed the bug by replacing

`Field("source-ip.raw", 4, "16s"),
 Field("destination-ip.raw", 4, "16s")`

with,

`Field("source-ip.raw", 16, "16s"),
    Field("destination-ip.raw", 16, "16s")`

**Comment by jasonish** [comment]
See #29
