### ISSUE TITLE
Please add an explicit LICENSE file to the project

### ISSUE THREAD

**Issue by marcindulak** [jasonish/py-idstools#32]
This is a request encouraged by Fedora packaging policy

https://bugzilla.redhat.com/show_bug.cgi?id=1398369
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

**Comment by jasonish** [comment]
Does this satisfy the requirement?

https://github.com/jasonish/py-idstools/commit/cae8f4b7d2e3f4d199c69c65fe8698b354f9d2bb

**Comment by marcindulak** [comment]
yes, thanks

**Comment by jasonish** [comment]
If all this checks out for you, I could tag a new release and push it up.

**Comment by marcindulak** [comment]
I would also like to get https://github.com/jasonish/py-idstools/pull/35 :)
