### ISSUE TITLE
python3: problem with encoding argument in u2eve json.dumps

### ISSUE THREAD

**Issue by marcindulak** [jasonish/py-idstools#36]
CentOS7, python 3.4.5 -  have a problem with https://github.com/jasonish/py-idstools/blob/5862a936af07b37458b1fc3719f9ade065b283f1/idstools/scripts/u2eve.py#L302
The error is not clear:

    Failed to encode record as JSON: __init__() got an unexpected keyword argument 'encoding':

but looking at https://docs.python.org/3/library/json.html#basic-usage json.dumps does not have the encoding argument, and encoding in json.loads is deprecated.

**Comment by jasonish** [comment]
Should be fixed. Will wait for you to confirm before closing.

**Comment by marcindulak** [comment]
Converted a few unified2 logs using u2eve and python 2.7.5, 3.4.5 on CentOS7, and python 2.6.6 on CentOS6, seems working.
