### ISSUE TITLE
eve2pcap.py: problem parsing timezone

### ISSUE THREAD

**Issue by marcindulak** [jasonish/py-idstools#37]
This fails:

    python2 /usr/bin/idstools-eve2pcap merged.log.eve -o merged.log.eve2pcap --dlt RAW
    python3 /usr/bin/idstools-eve2pcap merged.log.eve -o merged.log.eve2pcap --dlt RAW

    ValueError: time data '2017-01-02T09:51:30.644790+0100' does not match format '%Y-%m-%dT%H:%M:%S.%f-0600'

with the following `merged.log.eve`:

    {"timestamp": "2017-01-02T09:51:30.644790+0100", "sensor_id": 0, "event_type": "alert", "src_ip": "10.255.2.100", "src_port": 50621, "dest_ip": "10.255.2.160", "dest_port": 80, "proto": "TCP", "flow_id": 100663492, "alert": {"action": "allowed", "gid": 1, "signature_id": 10000002, "rev": 1, "signature": null, "category": null, "severity": 0}, "packet": "RQAAPBCRQABABg8qCv8CZAr/AqDFvQBQfykbqgAAAACgAnIQTs0AAAIEBbQEAggKAAULOwAAAAABAwMH"}

The problem is in https://github.com/jasonish/py-idstools/blob/5862a936af07b37458b1fc3719f9ade065b283f1/idstools/scripts/eve2pcap.py#L133

On python >= 3.2 one could do:

    dt = datetime.strptime(timestamp, "%Y-%m-%dT%H:%M:%S.%f%z")

but for both python2 and python3 maybe this?

    from dateutil import parser
    dt = parser.parse(timestamp)

**Comment by jasonish** [comment]
Thanks, use dateutil as a fix for now.
