### ISSUE TITLE
Feature Request: Suricata version override for rulecat?

### ISSUE THREAD

**Issue by valorcz** [jasonish/py-idstools#38]
I am merging Suricata ET rules on a server where Suricata daemon is not present, but I know which version of it runs on the boxes. However, rulecat doesn't use '-enhanced' ruleset in such a case, it goes with '-1.3' only.

Would it be possible to add an option with Suricata version override? Or just an option instructing rulecat to download and use the enhanced ruleset?

**Comment by jasonish** [comment]
For now you could specify the URL with the --url parameter, that will override the default URL used which does take the Suricata version into account.

**Comment by valorcz** [comment]
Great point, thanks!

**Comment by jasonish** [comment]
There is now a "--suricata-version <some-version>" command line argument to idstools-rulecat.

Commit:
https://github.com/jasonish/py-idstools/commit/02db0c62133efc47ed793434b4180d452e8b6980

Included in idstools v0.5.6.
