### ISSUE TITLE
Two writers, one file?

### ISSUE THREAD

**Issue by DigiAngel** [jasonish/py-idstools#48]
Is that possible?  Say I have u2eve reading two separate u2 files from two different snort instances....can I write to just one json file?  Or do I have to write to 2 separate ones?  Thanks Jason!

**Comment by jasonish** [comment]
No, it doesn't. That would require locking which can vary from platform to platform so is outside the scope of this library.

**Comment by DigiAngel** [comment]
Cool thanks...I figured that would be the case.
