### ISSUE TITLE
Improvement: rulecat report only if needed

### ISSUE THREAD

**Issue by sevdog** [jasonish/py-idstools#49]
Rulecat script when using the option `--merged` always generate a report [as you can see in the code](https://github.com/jasonish/py-idstools/blob/master/idstools/scripts/rulecat.py#L416), WHICH is logged with level `INFO`.

If the option `-q` or `--quiet` is given this results in an unnecessary execution, because the report is generated but never logged, because the loggin level raises to `WARNING`.

This code shoul be preceeeded by an `if` statement that checks if the logging level will permit report display before generating it.

**Comment by jasonish** [comment]
Thanks. Fix applied. Report will not be generated with --quiet.  I might have to rethink the report generation. Its only a half done feature anyways, with the idea of generating a full detailed report.
