### ISSUE TITLE
Missing tag or release for 0.6.2

### ISSUE THREAD

**Issue by sevdog** [jasonish/py-idstools#60]
As shown in below screnshots there is no tag nor version for `0.6.2`, even if it is released on pip.
![image](https://user-images.githubusercontent.com/13779643/32771803-37c9560e-c924-11e7-8a77-3448a2fd8ad6.png)
![image](https://user-images.githubusercontent.com/13779643/32771838-58a01e12-c924-11e7-8972-ee3056fa7e0b.png)

**Comment by jasonish** [comment]
Thanks for the heads up. Fixed.
