### ISSUE TITLE
support for spaces in list of hosts

### ISSUE THREAD

**Issue by 0xmilkmix** [jasonish/py-idstools#65]
# problem
From suricata documentation, [source-and-destination](http://suricata.readthedocs.io/en/latest/rules/intro.html#source-and-destination) can be a list containing spaces in rules

# solution
create regexp to match either single host or list of hosts

# attempt
- on my [fork's branch](https://github.com/0xmilkmix/py-idstools/blob/support_space_in_list/idstools/rule.py#L59)
- seems to work but test_rulecat takes forever so we can probably write something smarter for the regexp

**Comment by jasonish** [comment]
Regular expressions aren't the best here. Can you try my "develop" branch? I've reduced the use of re's and added a simple state based parser for the header that works in about the same amount of time.

**Comment by 0xmilkmix** [comment]
neat! indeed that the best way to do it. I'm writing a port of your lib in [php](https://github.com/0xmilkmix/MISP/blob/f6d4839123d393d4fcb91de28e5295cef65c70eb/app/Lib/Tools/SuricataRuleFormat.php) for MISP (perform some validations on rules format). I'll switch to states/loops as well
