### ISSUE TITLE
Recent versions of Snort unified2 not supported.

### ISSUE THREAD

**Issue by deepakrana47** [jasonish/py-idstools#72]
Hello,

I am trying to convert snort (=2.9.11) log to json file but getting error on python 2.7.12 with idstools (=0.6.3)

the code:

`
#!/usr/bin/python
from idstools import unified2

reader = unified2.SpoolRecordReader("/var/log/snort",
    "snort.log", follow=True)
for record in reader:
    if isinstance(record, unified2.Event):
        print("Event:")
    elif isinstance(record, unified2.Packet):
        print("Packet:")
    elif isinstance(record, unified2.ExtraData):
        print("Extra-Data:")
    print(record)
`

error:
**
Traceback (most recent call last):
  File "/home/zero/Desktop/log_2_json/for_snort.py", line 6, in <module>
    for record in reader:
  File "/home/zero/.local/lib/python2.7/site-packages/idstools/unified2.py", line 846, in iter_next
    record = self.next()
  File "/home/zero/.local/lib/python2.7/site-packages/idstools/unified2.py", line 817, in next
    record = self.reader.next()
  File "/home/zero/.local/lib/python2.7/site-packages/idstools/unified2.py", line 610, in next
    return read_record(self.fileobj)
  File "/home/zero/.local/lib/python2.7/site-packages/idstools/unified2.py", line 571, in read_record
    raise UnknownRecordType(rtype)
idstools.unified2.UnknownRecordType: Unknown record type: 3569595041
**

my snort log directory have files:
**
ls /var/log/snort
archived_logs  snort.log.1547718241  snort.log.1547725234
**
help me man.

**Comment by jasonish** [comment]
This version of Snort must have a new record that _idstools_ is not familiar with.  I don't actively run Snort anymore, so will need to rely on someone giving me a unified2 log file with this error. Are you able to share your log file? You can send it to me privately.

**Comment by deepakrana47** [comment]
thanks for the reply @jasonish.

**Comment by ArthanJans** [comment]
I'm also having this problem. I was wondering if a solution was found?

**Comment by deepakrana47** [comment]
the _idstools_ did not work for me, so i had to stop my work with snort.

**Comment by jasonish** [comment]
So newer versions of the Snort unified2 are not supported by idstools. I do not plan to do this work myself, but will accept patches provided with a test unified2 file to verify.
