### ISSUE TITLE
Connection with suricata-update

### ISSUE THREAD

**Issue by vpiserchia** [jasonish/py-idstools#78]
Hello @jasonish

I have a question, how this code relates with the one used in ```suricata-update```.
I see there are many differences, so I do not understand what is the future for this one

thanks for any answer
vito

**Comment by jasonish** [comment]
The only similarities would be in the "rulecat" tool, which was the foundation of "suricata-update".  There are some other tools in here that are not part of Suricata-Update, however, I don't really use this anymore so no new work is happening on it, and I rely on others to report/fix issues.

**Comment by vpiserchia** [comment]
Thank you very much for your time
