### ISSUE TITLE
Add .md5 extension between URL's filename and its parameters 

### ISSUE THREAD

**Issue by petiepooo** [jasonish/py-idstools#81]
The function below blindly adds a ".md5" to the end of the URL, assuming it has no parameters:
https://github.com/jasonish/py-idstools/blob/a97393d38f3a69fb34ca962918a33688f58c22f8/idstools/scripts/rulecat.py#L256-L258

However, some URLs require parameters, like an oinkcode.  It makes sense for the filename extension to be after the filename, but before the question mark character that signifies the start of the parameters.  Eg. if the URL is **hxxps://example.com/download/rules.gz?oinkcode=g1ty0ur0wn** the URL for the hash would be **hxxps://example.com/download/rules.gz.md5?oinkcode=g1ty0ur0wn**

If there are no parameters specified in the URL, then the .md5 extension should be appended to the end as it is.

**Comment by jasonish** [comment]
Great, thanks for the PR. Tested with a Snort registered rule set.
